"use client";

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { procurementApi } from "@/lib/api";
import { formatCurrency, cn } from "@/lib/utils";
import {
  ShoppingCart, CheckCircle2, XCircle, Truck, Clock, Package,
  ChevronLeft, ChevronRight, Eye, Loader2, RefreshCw,
} from "lucide-react";
import { toast } from "sonner";
import { useState } from "react";

const statusConfig: Record<string, { label: string; cls: string; icon: React.ElementType }> = {
  PENDING_APPROVAL: { label: "Pending Approval", cls: "badge-yellow", icon: Clock },
  APPROVED:         { label: "Approved",          cls: "badge-blue",   icon: CheckCircle2 },
  ORDERED:          { label: "Ordered",           cls: "badge-purple", icon: Package },
  DELIVERED:        { label: "Delivered",         cls: "badge-green",  icon: Truck },
  REJECTED:         { label: "Rejected",          cls: "badge-red",    icon: XCircle },
};

const STATUSES = ["ALL", "PENDING_APPROVAL", "APPROVED", "ORDERED", "DELIVERED", "REJECTED"];
const PAGE_SIZE = 10;

export function PurchaseOrdersView() {
  const [filter, setFilter] = useState("ALL");
  const [page, setPage]     = useState(1);
  const qc = useQueryClient();

  const { data, isLoading, isError, refetch, isFetching } = useQuery({
    queryKey: ["purchase-orders", filter],
    queryFn: () => procurementApi.getPOs(filter !== "ALL" ? { status: filter } : {}),
    refetchInterval: 10000,
  });

  const { data: summary } = useQuery({
    queryKey: ["po-summary"],
    queryFn: procurementApi.getSummary,
    refetchInterval: 15000,
  });

  const updateStatus = useMutation({
    mutationFn: ({ id, status, by }: { id: number; status: string; by: string }) =>
      procurementApi.updateStatus(id, { status, performed_by: by }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["purchase-orders"] });
      qc.invalidateQueries({ queryKey: ["po-summary"] });
      toast.success("Status updated");
    },
    onError: () => toast.error("Failed to update status"),
  });

  const pos       = data?.purchase_orders ?? [];
  const total     = data?.total ?? 0;
  const paged     = pos.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  const totalPages = Math.max(1, Math.ceil(pos.length / PAGE_SIZE));
  const stats     = summary?.stats ?? {};

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Purchase Orders</h1>
          <p className="text-sm text-slate-500 mt-0.5">Generated by Agent 4 — live from procurement_db</p>
        </div>
        <button onClick={() => refetch()} className="btn-secondary">
          <RefreshCw size={14} className={cn(isFetching && "animate-spin")} /> Refresh
        </button>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: "Total POs",     value: stats.total_pos    ?? 0, icon: ShoppingCart, color: "bg-brand-50 text-brand-600" },
          { label: "Total Value",   value: formatCurrency(stats.total_value ?? 0), icon: Package,      color: "bg-emerald-50 text-emerald-600" },
          { label: "Pending",       value: stats.pending      ?? 0, icon: Clock,        color: "bg-amber-50 text-amber-600" },
          { label: "Approved",      value: stats.approved     ?? 0, icon: CheckCircle2, color: "bg-blue-50 text-blue-600" },
        ].map(card => (
          <div key={card.label} className="stat-card">
            <div className={cn("w-9 h-9 rounded-lg flex items-center justify-center mb-3", card.color)}>
              <card.icon size={16} />
            </div>
            <p className="text-xl font-bold text-slate-900">{card.value}</p>
            <p className="text-xs text-slate-500 mt-1">{card.label}</p>
          </div>
        ))}
      </div>

      {/* Filter tabs */}
      <div className="flex items-center gap-1 border-b border-slate-200 overflow-x-auto">
        {STATUSES.map(s => (
          <button key={s} onClick={() => { setFilter(s); setPage(1); }}
            className={cn(
              "px-3 py-2 text-xs font-semibold whitespace-nowrap border-b-2 -mb-px transition-colors",
              filter === s ? "border-brand-600 text-brand-600" : "border-transparent text-slate-500 hover:text-slate-700"
            )}>
            {s === "ALL" ? "All" : statusConfig[s]?.label ?? s}
          </button>
        ))}
      </div>

      {/* Table */}
      <div className="section-card overflow-hidden">
        {isLoading ? (
          <div className="flex items-center justify-center py-16">
            <Loader2 size={28} className="animate-spin text-slate-300" />
          </div>
        ) : isError ? (
          <div className="py-12 text-center text-sm text-red-500">
            Could not connect to Procurement Service.
          </div>
        ) : pos.length === 0 ? (
          <div className="py-12 text-center">
            <Package size={36} className="text-slate-200 mx-auto mb-3" />
            <p className="text-sm text-slate-500">No purchase orders yet.</p>
            <p className="text-xs text-slate-400 mt-1">
              Go to the Dashboard and click "Run Agents" on a procurement request.
            </p>
          </div>
        ) : (
          <>
            <div className="overflow-x-auto">
              <table className="w-full data-table">
                <thead>
                  <tr>
                    <th>PO Number</th>
                    <th>Item</th>
                    <th>Vendor</th>
                    <th>Qty</th>
                    <th>Total</th>
                    <th>Status</th>
                    <th>Delivery</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {paged.map((po: any) => {
                    const sc = statusConfig[po.status] ?? statusConfig.PENDING_APPROVAL;
                    const Icon = sc.icon;
                    return (
                      <tr key={po.id}>
                        <td className="font-mono text-xs text-slate-600">{po.po_number}</td>
                        <td className="font-medium text-slate-800 max-w-[150px] truncate">{po.item_name}</td>
                        <td className="text-slate-600 max-w-[140px] truncate">{po.vendor_name}</td>
                        <td className="text-slate-600">{po.quantity?.toLocaleString("en-IN")}</td>
                        <td className="font-semibold text-slate-900">{formatCurrency(po.total_price)}</td>
                        <td>
                          <span className={cn("badge gap-1", sc.cls)}>
                            <Icon size={10} />{sc.label}
                          </span>
                        </td>
                        <td className="text-xs text-slate-400">{po.delivery_date_expected}</td>
                        <td>
                          {po.status === "PENDING_APPROVAL" && (
                            <div className="flex gap-1">
                              <button
                                onClick={() => updateStatus.mutate({ id: po.id, status: "APPROVED", by: "manager" })}
                                className="px-2 py-1 text-[11px] font-semibold bg-emerald-600 text-white rounded-md hover:bg-emerald-700">
                                Approve
                              </button>
                              <button
                                onClick={() => updateStatus.mutate({ id: po.id, status: "REJECTED", by: "manager" })}
                                className="px-2 py-1 text-[11px] font-semibold bg-white text-red-600 border border-red-200 rounded-md hover:bg-red-50">
                                Reject
                              </button>
                            </div>
                          )}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
            <div className="flex items-center justify-between px-5 py-3 border-t border-slate-100">
              <p className="text-xs text-slate-400">
                {total} total • showing {(page-1)*PAGE_SIZE+1}–{Math.min(page*PAGE_SIZE, pos.length)}
              </p>
              <div className="flex items-center gap-1">
                <button onClick={() => setPage(p => Math.max(1,p-1))} disabled={page===1}
                  className="btn-ghost p-1.5 disabled:opacity-40"><ChevronLeft size={14}/></button>
                {Array.from({length:totalPages},(_,i)=>i+1).map(n=>(
                  <button key={n} onClick={()=>setPage(n)}
                    className={cn("w-7 h-7 text-xs rounded-md font-medium",
                      n===page?"bg-brand-600 text-white":"text-slate-500 hover:bg-slate-100")}>{n}</button>
                ))}
                <button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages}
                  className="btn-ghost p-1.5 disabled:opacity-40"><ChevronRight size={14}/></button>
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
