"use client";

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useSearchParams } from "next/navigation";
import { procurementApi } from "@/lib/api";
import { formatCurrency, cn } from "@/lib/utils";
import {
  ShoppingCart, CheckCircle2, XCircle, Truck, Clock, Package,
  ChevronLeft, ChevronRight, Eye, Loader2, RefreshCw, Download,
  ShieldCheck, FileText, Trash2, X,
} from "lucide-react";
import { toast } from "sonner";
import { useState, useMemo } from "react";

const statusConfig: Record<string, { label: string; cls: string; icon: React.ElementType }> = {
  PENDING_APPROVAL: { label: "Pending Approval", cls: "badge-yellow", icon: Clock },
  APPROVED:         { label: "Approved",          cls: "badge-green",  icon: CheckCircle2 },
  ORDERED:          { label: "Ordered",           cls: "badge-purple", icon: Package },
  DELIVERED:        { label: "Delivered",         cls: "badge-blue",   icon: Truck },
  REJECTED:         { label: "Rejected",          cls: "badge-red",    icon: XCircle },
};

const tierConfig: Record<string, { label: string; cls: string }> = {
  TIER_1_OFFICER:  { label: "Tier 1 (< ₹50k)", cls: "bg-blue-50 text-blue-700 border-blue-200" },
  TIER_2_MANAGER:  { label: "Tier 2 (₹50k-200k)", cls: "bg-amber-50 text-amber-700 border-amber-200" },
  TIER_3_DIRECTOR: { label: "Tier 3 (> ₹200k)", cls: "bg-purple-50 text-purple-700 border-purple-200" },
};

const STATUSES = ["ALL", "PENDING_APPROVAL", "APPROVED", "ORDERED", "DELIVERED", "REJECTED"];
const PAGE_SIZE = 10;

export function PurchaseOrdersView() {
  const searchParams = useSearchParams();
  const searchParam = searchParams?.get("search") || "";

  const [filter, setFilter] = useState("ALL");
  const [page, setPage]     = useState(1);
  const qc = useQueryClient();

  const { data, isLoading, isError, refetch, isFetching } = useQuery({
    queryKey: ["purchase-orders", filter],
    queryFn: () => procurementApi.getPOs(filter !== "ALL" ? { status: filter } : {}),
    refetchInterval: 10000,
  });

  const { data: summary } = useQuery({
    queryKey: ["po-summary"],
    queryFn: procurementApi.getSummary,
    refetchInterval: 15000,
  });

  const updateStatus = useMutation({
    mutationFn: ({ id, status, by }: { id: number; status: string; by: string }) =>
      procurementApi.updateStatus(id, { status, performed_by: by }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["purchase-orders"] });
      qc.invalidateQueries({ queryKey: ["po-summary"] });
      toast.success("Status updated");
    },
    onError: () => toast.error("Failed to update status"),
  });

  const deletePOMut = useMutation({
    mutationFn: (id: number) => procurementApi.deletePO(id),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["purchase-orders"] });
      qc.invalidateQueries({ queryKey: ["po-summary"] });
      toast.success("Purchase Order deleted");
    },
    onError: (err: any) => toast.error(`Failed to delete PO: ${err.message}`),
  });

  const clearPOsMut = useMutation({
    mutationFn: () => procurementApi.clearPOs(),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["purchase-orders"] });
      qc.invalidateQueries({ queryKey: ["po-summary"] });
      toast.success("All Purchase Orders cleared");
    },
    onError: (err: any) => toast.error(`Failed to clear POs: ${err.message}`),
  });

  const rawPos    = data?.purchase_orders ?? [];
  const pos       = useMemo(() => {
    if (!searchParam.trim()) return rawPos;
    const q = searchParam.toLowerCase();
    return rawPos.filter((p: any) =>
      p.po_number?.toLowerCase().includes(q) ||
      p.item_name?.toLowerCase().includes(q) ||
      p.vendor_name?.toLowerCase().includes(q)
    );
  }, [rawPos, searchParam]);

  const total     = pos.length;
  const paged     = pos.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  const totalPages = Math.max(1, Math.ceil(pos.length / PAGE_SIZE));
  const stats     = summary?.stats ?? {};

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Purchase Orders</h1>
          <p className="text-sm text-slate-500 mt-0.5">
            Generated by Agent 4 — rule-based vendor selection & DocuSign integration
          </p>
        </div>
        <div className="flex items-center gap-2">
          {pos.length > 0 && (
            <button
              onClick={() => {
                if (window.confirm("Clear all Purchase Orders from the database?")) {
                  clearPOsMut.mutate();
                }
              }}
              disabled={clearPOsMut.isPending}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-slate-600 hover:text-red-600 hover:bg-red-50 border border-slate-200 rounded-lg transition-colors"
            >
              <Trash2 size={13} />
              <span>Clear All POs</span>
            </button>
          )}
          <button onClick={() => refetch()} className="btn-secondary">
            <RefreshCw size={14} className={cn(isFetching && "animate-spin")} /> Refresh
          </button>
        </div>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: "Total POs",     value: stats.total_pos    ?? 0, icon: ShoppingCart, color: "bg-brand-50 text-brand-600" },
          { label: "Total Value",   value: formatCurrency(stats.total_value ?? 0), icon: Package,      color: "bg-emerald-50 text-emerald-600" },
          { label: "Pending",       value: stats.pending      ?? 0, icon: Clock,        color: "bg-amber-50 text-amber-600" },
          { label: "Approved",      value: stats.approved     ?? 0, icon: CheckCircle2, color: "bg-blue-50 text-blue-600" },
        ].map(card => (
          <div key={card.label} className="stat-card">
            <div className={cn("w-9 h-9 rounded-lg flex items-center justify-center mb-3", card.color)}>
              <card.icon size={16} />
            </div>
            <p className="text-xl font-bold text-slate-900">{card.value}</p>
            <p className="text-xs text-slate-500 mt-1">{card.label}</p>
          </div>
        ))}
      </div>

      {/* Filter tabs */}
      <div className="flex items-center gap-1 border-b border-slate-200 overflow-x-auto">
        {STATUSES.map(s => (
          <button key={s} onClick={() => { setFilter(s); setPage(1); }}
            className={cn(
              "px-3 py-2 text-xs font-semibold whitespace-nowrap border-b-2 -mb-px transition-colors",
              filter === s ? "border-brand-600 text-brand-600" : "border-transparent text-slate-500 hover:text-slate-700"
            )}>
            {s === "ALL" ? "All" : statusConfig[s]?.label ?? s}
          </button>
        ))}
      </div>

      {/* Table */}
      <div className="section-card overflow-hidden">
        {isLoading ? (
          <div className="flex items-center justify-center py-16">
            <Loader2 size={28} className="animate-spin text-slate-300" />
          </div>
        ) : isError ? (
          <div className="py-12 text-center text-sm text-red-500">
            Could not connect to Procurement Service.
          </div>
        ) : pos.length === 0 ? (
          <div className="py-12 text-center">
            <Package size={36} className="text-slate-200 mx-auto mb-3" />
            <p className="text-sm text-slate-500">No purchase orders yet.</p>
            <p className="text-xs text-slate-400 mt-1">
              Go to the Dashboard and click "Run Agents" on a procurement request.
            </p>
          </div>
        ) : (
          <>
            <div className="overflow-x-auto">
              <table className="w-full data-table">
                <thead>
                  <tr>
                    <th>PO Number</th>
                    <th>Item</th>
                    <th>Vendor</th>
                    <th>Total</th>
                    <th>Approval Routing</th>
                    <th>Status</th>
                    <th>Delivery</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {paged.map((po: any) => {
                    const sc = statusConfig[po.status] ?? statusConfig.PENDING_APPROVAL;
                    const Icon = sc.icon;
                    const tc = tierConfig[po.approval_tier] ?? tierConfig.TIER_1_OFFICER;
                    return (
                      <tr key={po.id}>
                        <td className="font-mono text-xs text-slate-700 font-semibold">
                          {po.po_number}
                        </td>
                        <td className="font-medium text-slate-800 max-w-[140px] truncate">
                          {po.item_name}
                          <p className="text-[11px] text-slate-400 font-normal">{po.quantity?.toLocaleString("en-IN")} units</p>
                        </td>
                        <td className="text-slate-600 max-w-[130px] truncate">{po.vendor_name}</td>
                        <td className="font-bold text-slate-900">{formatCurrency(po.total_price)}</td>
                        <td>
                          <div className="space-y-0.5">
                            <span className={cn("inline-flex items-center px-2 py-0.5 rounded text-[10px] font-semibold border", tc.cls)}>
                              {tc.label}
                            </span>
                            <p className="text-[10px] text-slate-400 truncate max-w-[130px]">
                              {po.assigned_approver_name || "Procurement Officer"}
                            </p>
                          </div>
                        </td>
                        <td>
                          <span className={cn("badge gap-1", sc.cls)}>
                            <Icon size={10} />{sc.label}
                          </span>
                        </td>
                        <td className="text-xs text-slate-400">{po.delivery_date_expected}</td>
                        <td>
                          <div className="flex items-center gap-1.5 flex-wrap">
                            {/* Download Button */}
                            <a
                              href={procurementApi.getPO_Download_Url(po.id)}
                              download={`${po.po_number}.pdf`}
                              className="inline-flex items-center gap-1 px-2.5 py-1 text-xs font-semibold text-slate-700 bg-white hover:bg-slate-50 hover:text-brand-600 border border-slate-200 rounded-lg shadow-sm transition-colors"
                              title={po.signed_document_url ? "Download Signed PO from MinIO" : "Download PO PDF"}
                            >
                              <Download size={12} className="text-brand-600" />
                              <span>Download</span>
                              {po.signed_document_url && (
                                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" title="Digitally signed & stored in MinIO" />
                              )}
                            </a>

                            {/* Preview in browser */}
                            <button
                              onClick={() => window.open(procurementApi.getPO_PDF_Url(po.id), "_blank")}
                              className="p-1 text-slate-400 hover:text-slate-700 hover:bg-slate-100 rounded-md transition-colors"
                              title="Preview PDF"
                            >
                              <Eye size={13} />
                            </button>

                            {/* Delete PO */}
                            <button
                              onClick={() => {
                                if (window.confirm(`Delete purchase order ${po.po_number}?`)) {
                                  deletePOMut.mutate(po.id);
                                }
                              }}
                              className="p-1 text-slate-300 hover:text-red-600 hover:bg-red-50 rounded-md transition-colors"
                              title="Delete PO"
                            >
                              <Trash2 size={13} />
                            </button>

                            {/* Status quick actions */}
                            {po.status === "PENDING_APPROVAL" && (
                              <div className="flex gap-1 ml-1">
                                <button
                                  onClick={() => updateStatus.mutate({ id: po.id, status: "APPROVED", by: "manager" })}
                                  className="px-2 py-1 text-[11px] font-semibold bg-emerald-600 text-white rounded-md hover:bg-emerald-700">
                                  Approve
                                </button>
                                <button
                                  onClick={() => updateStatus.mutate({ id: po.id, status: "REJECTED", by: "manager" })}
                                  className="px-2 py-1 text-[11px] font-semibold bg-white text-red-600 border border-red-200 rounded-md hover:bg-red-50">
                                  Reject
                                </button>
                              </div>
                            )}
                          </div>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
            <div className="flex items-center justify-between px-5 py-3 border-t border-slate-100">
              <p className="text-xs text-slate-400">
                {total} total • showing {(page-1)*PAGE_SIZE+1}–{Math.min(page*PAGE_SIZE, pos.length)}
              </p>
              <div className="flex items-center gap-1">
                <button onClick={() => setPage(p => Math.max(1,p-1))} disabled={page===1}
                  className="btn-ghost p-1.5 disabled:opacity-40"><ChevronLeft size={14}/></button>
                {Array.from({length:totalPages},(_,i)=>i+1).map(n=>(
                  <button key={n} onClick={()=>setPage(n)}
                    className={cn("w-7 h-7 text-xs rounded-md font-medium",
                      n===page?"bg-brand-600 text-white":"text-slate-500 hover:bg-slate-100")}>{n}</button>
                ))}
                <button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages}
                  className="btn-ghost p-1.5 disabled:opacity-40"><ChevronRight size={14}/></button>
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
